#!/bin/bash
####
#TODO: check for installation of bash-completion
__check-cmd-exists() {
	command -v "${1}" >/dev/null 2>&1 || { return 1; }
}
__echo-need-cmd() {
echo "Installing \"note\" requires \"${1}\" to be installed." >&2
}
__note-init-func () {
	local SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
	local DIR=$(dirname ${SCRIPTPATH}) # TODO hardcoded
	local NOTE_SCR_PATH='/usr/local/bin/note'
	local NOTE_CNFG=~/'.config/notes/config'
	local NOTE_SRC=note-source
	local LINE='[ -f '"${SCRIPTPATH}"'/'"${NOTE_SRC}"' ] && . '"${SCRIPTPATH}"/"${NOTE_SRC}"
	local FILE=~/.bash_aliases
	local INSTALL_NOTES=0
	#### place note cmd script somewhere in PATH
	if [ ! -f "${NOTE_SCR_PATH}" ]; then
		echo "${NOTE_SCR_PATH}" does not exist, creating...
		sudo ln -s "${SCRIPTPATH}"/note "${NOTE_SCR_PATH}" || return 1
	fi
	#### add line to .bash_aliases if needed to source NOTE_SRC
	[ ! -f "${FILE}" ] && echo "${FILE}" does not exist, creating... ; touch "${FILE}"
	grep -qF -- "${LINE}" "${FILE}" || (echo -e "\n${LINE}" >> "${FILE}" && echo "${NOTE_SRC}" added to "${FILE}")
	#### check for required commands for notes install
	__check-cmd-exists make || (__echo-need-cmd make; exit 1)
	__check-cmd-exists curl || (__echo-need-cmd curl; exit 1)
	__check-cmd-exists pkg-config || (__echo-need-cmd pkg-config; exit 1)
	__check-cmd-exists notes || INSTALL_NOTES=1
	if [ "${INSTALL_NOTES}" -eq 1 ]; then
		echo "prerequisite \"notes\" for \"note\" installation will be attempted"
		if [ -f ${DIR}/third-party/notes/install.sh ] ; then
			chmod 755 ${DIR}/third-party/notes/install.sh # TODO: hardcoded path
			sudo bash ${DIR}/third-party/notes/install.sh
		else
			echo "notes directory not installed or nothing at ${DIR}/third_party/notes/install.sh" && return 1
		fi
	fi
	#### config file generation
	if [ ! -f "${NOTE_CNFG}" ]; then
		echo "${NOTE_CNFG}" does not exist, creating...
		sudo ln -s "${SCRIPTPATH}"/config "${NOTE_CNFG}"
	else # TODO take user input and/or make option to remove non symlink file
		test -h "${NOTE_CNFG}" || (rm "${NOTE_CNFG}" ; sudo ln -s "${SCRIPTPATH}"/config "${NOTE_CNFG}")
	fi
	echo "${0} has finished installing successfully"
}
####
__note-init-func
exit "${?}"
